name: Deploy Preview

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend

jobs:
  update:
    name: Publish EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish Update
        run: eas update --branch main --message "Auto-update from GitHub commit ${{ github.sha }}"
